#!/usr/bin/env bash
# Pull public threat feeds into the BackMaster blocklist directory.
#
# Each feed lands in its own *-feed.txt file, named so that the popup wording
# matches the feed's category. Hand-curated files are never touched.
#
#   sudo tools/update-blocklists.sh
#   sudo systemctl reload backmasterd    # or: backmasterctl reload

set -uo pipefail

DIR="${BACKMASTER_BLOCKLIST_DIR:-/etc/backmaster/blocklists}"
UA="BackMaster-blocklist-updater/1.0"

if [[ ! -d "$DIR" ]]; then
    echo "error: $DIR does not exist" >&2
    echo "       set BACKMASTER_BLOCKLIST_DIR to point somewhere else" >&2
    exit 1
fi
if [[ ! -w "$DIR" ]]; then
    echo "error: $DIR is not writable, re-run with sudo" >&2
    exit 1
fi

# name|url  -- the name becomes <name>-feed.txt and drives the popup wording.
FEEDS=(
    "malware|https://urlhaus.abuse.ch/downloads/hostfile/"
    "phishing|https://phishing.army/download/phishing_army_blocklist_extended.txt"
    "malvertising|https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
)

failed=0
for entry in "${FEEDS[@]}"; do
    name="${entry%%|*}"
    url="${entry#*|}"
    out="$DIR/${name}-feed.txt"
    tmp="$(mktemp)"

    printf '%-14s %s\n' "$name" "fetching..."
    if ! curl --fail --silent --show-error --location --max-time 120 \
              --user-agent "$UA" "$url" -o "$tmp"; then
        echo "  failed, keeping the previous $out" >&2
        rm -f "$tmp"
        failed=1
        continue
    fi

    # Feeds are a mix of hosts-file and bare-domain formats. Normalise both to
    # one domain per line and drop the loopback entries every hosts file starts
    # with, which would otherwise blocklist localhost.
    {
        echo "# generated by update-blocklists.sh on $(date -Iseconds)"
        echo "# source: $url"
        awk '
            /^[[:space:]]*#/ { next }
            /^[[:space:]]*$/ { next }
            {
                sub(/\r$/, "")
                host = ($1 == "0.0.0.0" || $1 == "127.0.0.1" || $1 == "::1") ? $2 : $1
                if (host == "" ) next
                if (host == "localhost" || host == "localhost.localdomain") next
                if (host == "broadcasthost" || host == "ip6-localhost") next
                if (host ~ /^ip6-/) next
                if (host !~ /\./) next
                print tolower(host)
            }
        ' "$tmp" | sort -u
    } > "$out.new"

    count=$(grep -cv '^#' "$out.new" || true)
    if [[ "$count" -lt 10 ]]; then
        echo "  only $count entries parsed, refusing to install" >&2
        rm -f "$out.new" "$tmp"
        failed=1
        continue
    fi

    mv "$out.new" "$out"
    chmod 0644 "$out"
    rm -f "$tmp"
    printf '%-14s %s entries -> %s\n' "$name" "$count" "$out"
done

echo
if command -v backmasterctl >/dev/null 2>&1; then
    echo "Applying:"
    backmasterctl reload >/dev/null 2>&1 \
        && echo "  daemon reloaded" \
        || echo "  daemon not running, the new lists load on next start"
else
    echo "Run 'backmasterctl reload' to apply."
fi

exit "$failed"
